=== davidjeck/graphicsbook/graphicstext/graphicstext.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY pi "&#960;">       <!-- these are used by graphicstext.xml but are redefined in graphicstext-tex.xml -->
<!ENTITY Omega "&#937;">
<!ENTITY Theta "&#920;">
<!ENTITY nbsp "&#160;">
<!ENTITY BigOh "O">
<!ENTITY dots "...">
<!ENTITY mdash "&#8212;">
<!ENTITY middot "&#183;">
<!ENTITY minus "&#8722;">
<!ENTITY times "&#215;">
<!ENTITY leftquote '"'>
<!ENTITY textitlebreak "">
<!ENTITY newcodestyle "red">

<!ENTITY includes SYSTEM "graphicstext-xml-includes.txt">

<!ENTITY % simpletextitem "b|i|u|big|sub|sup|code|web|tex|sourceref|demoref|ptype|classname|atype|word|tag">
<!ENTITY % textitem "b|i|u|big|sub|sup|code|br|a|localref|web|tex|sourceref|demoref|ptype|newword|word|tag|codedef|bnf|newcode|classname|atype|prog">
<!ENTITY % innertext "(#PCDATA|%textitem;)*">
<!ENTITY % simpletext "(#PCDATA|%simpletextitem;)*">
<!ENTITY % text "(p|p1|np|pre|break|img|ul|ol|narrower|centered|imageclear|webdiv|texdiv|demo)*">

<!ELEMENT graphicstext (preface?,chapter*,appendix*,source?,glossary?)>
<!ELEMENT preface (%text;)>
<!ELEMENT intro (%text;)>

<!ELEMENT chapter (intro,section*,exercises?,quiz?)>
<!ATTLIST chapter 
	id ID #REQUIRED
	title CDATA #REQUIRED
	shorttitle CDATA #IMPLIED>

<!ELEMENT appendix (intro,section*)>
<!ATTLIST appendix 
	id ID #REQUIRED
	title CDATA #REQUIRED
	shorttitle CDATA #IMPLIED>

<!ELEMENT section (%text;,subsection*,endchapter?)>
<!ATTLIST section 
	id ID #REQUIRED
	title CDATA #REQUIRED
	shorttitle CDATA #IMPLIED>

<!ELEMENT subsection (%text;)>
<!ATTLIST subsection 
	id ID #REQUIRED
	title CDATA #REQUIRED
	shorttitle CDATA #IMPLIED>
<!ELEMENT endchapter EMPTY>

<!ELEMENT source (%text;,subsection*)>

<!ELEMENT glossary (gitem*)>

<!ELEMENT gitem (#PCDATA)>
<!ATTLIST gitem
   term CDATA #REQUIRED>

<!ELEMENT newword %simpletext;>  <!-- the term is the corresponding glossary item, used when it is not identical to the element content -->
<!ATTLIST newword
   term CDATA #IMPLIED>

<!ELEMENT word %simpletext;>  <!-- the term is the corresponding glossary item, used when it is not identical to the element content -->
<!ATTLIST word
   term CDATA #IMPLIED>

<!ELEMENT fudgeref EMPTY>
<!ATTLIST fudgeref
   id ID #REQUIRED
   text CDATA #REQUIRED>

<!ELEMENT exercises (exercise*)>
<!ELEMENT exercise (exercise-question,exercise-discuss,exercise-code)>
<!ATTLIST exercise
    id ID #IMPLIED>
<!ELEMENT exercise-question %text;>
<!ELEMENT exercise-discuss %text;>
<!ELEMENT exercise-code %text;>

<!ELEMENT quiz (question*)>
<!ELEMENT question (ques,ans)>
<!ELEMENT ques %text;>
<!ELEMENT ans %text;>

<!ELEMENT pre %innertext;>
<!ATTLIST pre
	xml:space CDATA #FIXED "preserve">
	
<!ELEMENT prog %innertext;>
<!ATTLIST prog
	xml:space CDATA #FIXED "preserve"
	name CDATA #REQUIRED>

<!ELEMENT p %innertext;>
<!ATTLIST p 
    align CDATA #IMPLIED>
<!ELEMENT p1 %innertext;>  <!-- first paragraph, for separate styling -->
<!ELEMENT np %innertext;>  <!-- unindented paragraph -->

<!ELEMENT narrower %text;>
<!ATTLIST narrower
   margin CDATA #IMPLIED>

<!ELEMENT centered %text;>

<!ELEMENT localref (#PCDATA)>
<!ATTLIST localref
    href CDATA #REQUIRED>

<!ELEMENT sourceref (#PCDATA)>
<!ATTLIST sourceref
    href CDATA #REQUIRED>

<!ELEMENT demoref (#PCDATA)>
<!ATTLIST demoref
    href CDATA #REQUIRED>

<!ELEMENT a (#PCDATA)>
<!ATTLIST a
    href CDATA #REQUIRED>

<!ELEMENT img EMPTY>
<!ATTLIST img
    src CDATA #IMPLIED
    alt CDATA #IMPLIED
    width CDATA #IMPLIED
    height CDATA #IMPLIED
    bordered CDATA #IMPLIED
    align CDATA #IMPLIED
    tex CDATA #IMPLIED
    texscale CDATA #IMPLIED>
    
<!ELEMENT demo %text;>
<!ATTLIST demo
    src CDATA #REQUIRED
    width CDATA #REQUIRED
    height CDATA #REQUIRED>
    
<!ELEMENT ul (li*)>
<!ELEMENT ol (li*)>
<!ELEMENT li %innertext;>

<!ELEMENT br EMPTY>
<!ELEMENT break EMPTY>
<!ELEMENT imageclear EMPTY> <!-- adds a "br clear=all" in the web version -->
<!ELEMENT i %innertext;>
<!ELEMENT b %innertext;>
<!ELEMENT u %innertext;>
<!ELEMENT big %innertext;>
<!ELEMENT sup %innertext;>
<!ELEMENT sub %innertext;>
<!ELEMENT code %innertext;>
<!ELEMENT newcode %innertext;>
<!ELEMENT web %innertext;>   <!-- appears only in web version -->
<!ELEMENT tex %innertext;>   <!-- appears only in tex version -->
<!ELEMENT ptype %innertext;>   <!-- primitive type -->
<!ELEMENT bnf %innertext;>
<!ELEMENT classname (#PCDATA)>
<!ELEMENT atype (#PCDATA)>       <!-- array type -->
<!ELEMENT tag (#PCDATA)>   <!-- an HTML tag -->
<!ELEMENT codedef %innertext;>
<!ELEMENT webdiv %text;>   <!-- appears only in web version -->
<!ELEMENT texdiv %text;>   <!-- appears only in tex version -->

<!ENTITY source SYSTEM "source/source.xml">
<!ENTITY preface SYSTEM "preface.xml">
<!ENTITY glossary SYSTEM "glossary.xml">

<!ENTITY proglang_intro SYSTEM "a1-proglang/intro.xml">
<!ENTITY proglang_s1 SYSTEM "a1-proglang/s1.xml">
<!ENTITY proglang_s2 SYSTEM "a1-proglang/s2.xml">
<!ENTITY proglang_s3 SYSTEM "a1-proglang/s3.xml">

<!ENTITY blender_intro SYSTEM "a2-blender/intro.xml">
<!ENTITY blender_s1 SYSTEM "a2-blender/s1.xml">
<!ENTITY blender_s2 SYSTEM "a2-blender/s2.xml">
<!ENTITY blender_s3 SYSTEM "a2-blender/s3.xml">
<!ENTITY blender_s4 SYSTEM "a2-blender/s4.xml">

<!ENTITY gimp_intro SYSTEM "a3-gimp-inkscape/intro.xml">
<!ENTITY gimp_s1 SYSTEM "a3-gimp-inkscape/s1.xml">
<!ENTITY gimp_s2 SYSTEM "a3-gimp-inkscape/s2.xml">

<!ENTITY introduction_intro SYSTEM "c01-introduction/intro.xml">
<!ENTITY introduction_s1 SYSTEM "c01-introduction/s1.xml">
<!ENTITY introduction_s2 SYSTEM "c01-introduction/s2.xml">
<!ENTITY introduction_s3 SYSTEM "c01-introduction/s3.xml">
<!ENTITY introduction_s4 SYSTEM "c01-introduction/s4.xml">

<!ENTITY graphics2d_intro SYSTEM "c02-graphics2d/intro.xml">
<!ENTITY graphics2d_s1 SYSTEM "c02-graphics2d/s1.xml">
<!ENTITY graphics2d_s2 SYSTEM "c02-graphics2d/s2.xml">
<!ENTITY graphics2d_s3 SYSTEM "c02-graphics2d/s3.xml"> 
<!ENTITY graphics2d_s4 SYSTEM "c02-graphics2d/s4.xml">
<!ENTITY graphics2d_s5 SYSTEM "c02-graphics2d/s5.xml">
<!ENTITY graphics2d_s6 SYSTEM "c02-graphics2d/s6.xml">
<!ENTITY graphics2d_s7 SYSTEM "c02-graphics2d/s7.xml">

<!ENTITY gl1geom_intro SYSTEM "c03-gl1geom/intro.xml">
<!ENTITY gl1geom_s1 SYSTEM "c03-gl1geom/s1.xml">
<!ENTITY gl1geom_s2 SYSTEM "c03-gl1geom/s2.xml">
<!ENTITY gl1geom_s3 SYSTEM "c03-gl1geom/s3.xml">
<!ENTITY gl1geom_s4 SYSTEM "c03-gl1geom/s4.xml">
<!ENTITY gl1geom_s5 SYSTEM "c03-gl1geom/s5.xml">
<!ENTITY gl1geom_s6 SYSTEM "c03-gl1geom/s6.xml">

<!ENTITY gl1light_intro SYSTEM "c04-gl1light/intro.xml">
<!ENTITY gl1light_s1 SYSTEM "c04-gl1light/s1.xml">
<!ENTITY gl1light_s2 SYSTEM "c04-gl1light/s2.xml">
<!ENTITY gl1light_s3 SYSTEM "c04-gl1light/s3.xml">
<!ENTITY gl1light_s4 SYSTEM "c04-gl1light/s4.xml">

<!ENTITY threejs_intro SYSTEM "c05-threejs/intro.xml">
<!ENTITY threejs_s1 SYSTEM "c05-threejs/s1.xml">
<!ENTITY threejs_s2 SYSTEM "c05-threejs/s2.xml">
<!ENTITY threejs_s3 SYSTEM "c05-threejs/s3.xml">

<!ENTITY webgl_intro SYSTEM "c06-webgl/intro.xml">
<!ENTITY webgl_s1 SYSTEM "c06-webgl/s1.xml">
<!ENTITY webgl_s2 SYSTEM "c06-webgl/s2.xml">
<!ENTITY webgl_s3 SYSTEM "c06-webgl/s3.xml">
<!ENTITY webgl_s4 SYSTEM "c06-webgl/s4.xml">
<!ENTITY webgl_s5 SYSTEM "c06-webgl/s5.xml">

<!ENTITY webgl3d_intro SYSTEM "c07-webgl3d/intro.xml">
<!ENTITY webgl3d_s1 SYSTEM "c07-webgl3d/s1.xml">
<!ENTITY webgl3d_s2 SYSTEM "c07-webgl3d/s2.xml">
<!ENTITY webgl3d_s3 SYSTEM "c07-webgl3d/s3.xml">
<!ENTITY webgl3d_s4 SYSTEM "c07-webgl3d/s4.xml">
<!ENTITY webgl3d_s5 SYSTEM "c07-webgl3d/s5.xml">

<!ENTITY advanced_intro SYSTEM "c08-advanced/intro.xml">
<!ENTITY advanced_s1 SYSTEM "c08-advanced/s1.xml">
<!ENTITY advanced_s2 SYSTEM "c08-advanced/s2.xml">

=== davidjeck/graphicsbook/graphicstext/c07-webgl3d/intro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE intro SYSTEM "../graphicstext.dtd" >

<intro>

<p1>The previous chapter covered WebGL, but only in the context of
two-dimensional graphics.   As we move into 3D, we will have to
work with more complex <word term="geometric transform">transformations</word>.
For that, we will rely mainly on an open-source JavaScript library for 
vector and matrix math.  We will also need to implement
<word>lighting</word> and <word>material</word>, which we will
do directly in <word>GLSL</word>.</p1>

<p>We begin the chapter by duplicating most of the capabilities of <word>OpenGL</word>&nbsp;1.1
that were covered in <localref href="gl1geom"/> and <localref href="gl1light"/>.
But we will soon move beyond that by adding features such as
<word term="spotlight">spotlights</word>, <word>Phong shading</word>, and
<word>environment mapping</word>.</p>

</intro>

=== davidjeck/graphicsbook/graphicstext/c04-gl1light/intro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE intro SYSTEM "../graphicstext.dtd" >

<intro>

<p1>One of the goals of computer graphics is physical realism, that is, making
images that look like they could be photographs of reality.  This is not the only 
goal.  For example, for scientific visualization, the goal is to use computer 
graphics to present information accurately and clearly.  Artists can use computer
graphics to create abstract rather than realistic art.  However, realism is a
major goal of some of the most visible uses of computer graphics, such as video
games, movies, and advertising.</p1>

<p>One important aspect of physical realism is <word>lighting</word>:
the play of light and shadow, the way that light reflects from different 
<word term="material">materials</word>, the
way it can bend or be diffracted as it passes through translucent
objects.  The techniques that are used to produce the most realistic graphics
can take all these factors and more into account.</p>

<p>However, another goal of computer graphics is <i>speed</i>.  OpenGL, in particular,
was designed for <newword>real-time graphics</newword>, where the time that is available
for rendering an image is a fraction of a second.  For an animated movie, it's OK if
it takes hours to <word term="rendering">render</word> each frame.  But a video game is expected to
render sixty frames every second.  Even with the incredible speed of modern computer graphics
hardware, compromises are necessary to get that speed.  And thirty years ago, when OpenGL
was still new, the compromises were a lot bigger</p>

<p>In this chapter, we look at light and material in OpenGL 1.1.   You will learn how to
configure light sources and how to assign material properties to objects.  Material properties determine how
the objects interact with light.  And you will learn how to apply an image to a surface
as a <word>texture</word>.  The support for light, material, and texture in OpenGL 1.1
is relatively crude and incomplete, by today's standards.  But the concepts that it uses
still serve as the foundation for modern real-time graphics and, to a significant extent,
even for the most realistic computer graphics.</p>


</intro>

=== davidjeck/graphicsbook/graphicstext/c06-webgl/intro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE intro SYSTEM "../graphicstext.dtd" >

<intro>

<p1>In this chapter, we turn to <newword>WebGL</newword>, the version of <word>OpenGL</word>
for the Web.  <i>Three.js</i>, which was covered in the <localref href="threejs">previous chapter</localref>,
uses WebGL for 3D graphics.  Of course, it is more difficult to use WebGL directly, but doing
so gives you full control over the graphics hardware.  And learning it will be a good introduction
to modern graphics programming.  WebGL is very different from OpenGL&nbsp;1.1, which we 
studied in <localref href="gl1geom"/> and <localref href="gl1light"/>.  Nevertheless,
it will turn out that much of what you learned in previous chapters will carry over to
WebGL. </p1>

<p>It is not my intention to cover WebGL in its entirety.  There are many WebGL features
that I will not even mention, and many of those are important for more advanced computer
graphics.  However, I will cover the core features that are needed for 2D and 3D graphics,
along with a few of the more advanced aspects, as a bonus.</p>

<p>There are two versions of WebGL, both of them still in use.  WebGL 1.0 is based on 
OpenGL ES 2.0, a version of OpenGL designed for use on embedded systems such as 
smart phones and tablets.  OpenGL ES 1.0, the original OpenGL for embedded systems,
was very similar to OpenGL&nbsp;1.1.  However, the 2.0 version of OpenGL&nbsp;ES introduced
major changes.  It is actually a smaller, simpler <word>API</word> that puts more responsibility
on the programmer.  For example, functions for working with transformations, such
as <i>glRotatef</i> and <i>glPushMatrix</i>, were eliminated from the API, making the
programmer responsible for keeping track of transformations.  WebGL does not
use <i>glBegin/glEnd</i> to generate geometry, and it doesn't use function such
as <i>glColor*</i> or <i>glNormal*</i> to specify attributes of vertices. 
WebGL 1.0 is supported in almost every web browser.  (On some devices, WebGL might
be disabled because of hardware limitations.)</p>

<p>WebGL 2.0, which is based on OpenGL ES 3.0, is now supported on almost all devices that
suport WebGL&nbsp;1.0.  Most programs written for WebGL&nbsp;1.0 will
also work under WebGL&nbsp;2.0, so almost everything that you learn about the 1.0 version
will carry over to the newer version.  In this textbook, I will concentrate on WebGL&nbsp;1.0,
but I will also cover some of the new features of WebGL&nbsp;2.0.
I will try to make it clear when I am talking about features that only apply to WebGL&nbsp;2.0.</p>

<p>There are two sides to any WebGL program.  Part of the program is written in
<word>JavaScript</word>, the programming language for the web. The second part is
written in <word>GLSL</word>, a language for writing "shader" programs that run on the
<word>GPU</word>.  WebGL&nbsp;1.0 uses GLSL ES 1.00 (the
OpenGL Shader Language for Embedded Systems, version 1.00).  WebGL&nbsp;2.0 can use shader
programs written in GLSL ES 1.00, but it can also use GLSL ES 3.00, which has some
significant differences as well as new features.  I will try to always be clear about 
which language I am discussing.</p>

<p>For this introductory chapter about WebGL, we will stick to basic 
2D graphics.  You will learn about the structure of WebGL programs.  You will learn
most of the JavaScript side of the API, and you will learn how to write and use simple
shaders.  In the <localref href="webgl3d">next chapter</localref>, we will move
on to 3D graphics, and you will learn a great deal more about GLSL.</p>

</intro>

=== davidjeck/graphicsbook/graphicstext/a2-blender/intro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE intro SYSTEM "../graphicstext.dtd" >

<intro>

<p1>Blender is a free and open-source graphics program with a large
community of users.  It can be used to create and animate 3D 
scenes interactively.  It is a very complex and sophisticated program,
with advanced modeling and rendering tools, that can be used to
produce professional graphics and animation. This appendix looks
at just a small subset of its features.</p1>

<p>Blender can be downloaded from <a href="https://www.blender.org">blender.org</a>.
The site includes a great deal of information about what it can do
(<a href="https://www.blender.org/features/">blender.org/features</a>)
and how to use it (<a href="https://www.blender.org/support/">blender.org/support</a>).</p>

<p>I have included some work with Blender as part of my computer graphics courses since 2001,
as a supplement to the graphics programming that is the main topic of the course.
While we use only a small part of Blender's capabilities, I believe that it is useful
for students to have some experience with interactive 3D modeling.  It helps them develop their
ability to visualize in three dimensions, and it lets them see
the role that fundamental concepts such as transformations, lighting and material,
and textures play in real applications.
Most people are intimidated, at first, by Blender's complex interface, but it's
actually not difficult to learn how to use it for some basic tasks that are
relevant to this textbook. Many of my students have enjoyed using it and have gone on to learn 
enough about it to use it in a final project.
</p>

<p>Blender went through some significant changes between versions 2.79 and 2.8.
This appendix is based on Blender&nbsp;2.93, which is the current version as of
July, 2021.  However, most of the appendix should apply to any version between 
2.8 and 2.93.</p>

</intro>

=== davidjeck/graphicsbook/graphicstext/c05-threejs/intro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE intro SYSTEM "../graphicstext.dtd" >

<intro>

<p1><localref href="gl1geom"/> and <localref href="gl1light"/> introduced 3D graphics 
using <word>OpenGL</word>&nbsp;1.1.  Most of the ideas covered in those chapters remain relevant to modern
computer graphics, but there have been many changes and improvements since the early
days of OpenGL.  In <localref href="webgl"/> and <localref href="webgl3d"/>, we will be using <word>WebGL</word>,
a modern version of OpenGL that is used to create 3D graphics content for web pages.
And <localref href="webgpu"/> introduces <word>WebGPU</word>, a newer graphics <word>API</word> for the Web.</p1>

<p>WebGL is a low level language&mdash;even more so than OpenGL 1.1, since a WebGL program
has to handle a lot of the low-level implementation details that were handled internally
in the original version of OpenGL.  This makes WebGL much more flexible, but more difficult
to use.  We will soon turn to working
directly with WebGL.  However, before we do that, we will look
at a higher-level API for 3D web graphics that is built on top of WegGL:  
<i><newword>three.js</newword></i>.  There are several reasons for starting at this high level.
It will allow you to see how some of the things that you have learned are used in
a modern object-oriented graphics package.  It will allow me to introduce some new features such as
shadows and environment mapping.  It will let you work with a graphics library that
you might use in real web applications.
And it will be a break from the low-level detail we have been dealing with, before
we move on to an even lower level.</p>

<p>You can probably follow much of the discussion in this chapter without knowing 
JavaScript.  However, if you want to do any programming with <i>three.js</i> (or with 
WebGL or WebGPU), you need to know JavaScript.  The basics of the language are covered in
<localref href="proglang.3"/> in <localref href="proglang"/>.</p>

</intro>

=== davidjeck/graphicsbook/graphicstext/a1-proglang/intro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE intro SYSTEM "../graphicstext.dtd" >

<intro>

<p1>This appendix contains brief introductions to three programming languages that are used in the
textbook: Java, C, and JavaScript.   You should be very familiar with at least one of the
three languages before reading this textbook.  The three languages have something in common, so that
knowing one will make it easier to learn the others.  You should also be at least somewhat 
familiar with classes, objects, and object-oriented programming.</p1>

<p>The appendix is meant to help you 
get started with the languages that you don't already know.  Only some basic information about each
language is given&mdash;but hopefully enough to let you understand examples in the
book and to write some programs that use the graphics techniques that are covered.
You should at least be able to work with the sample programs that accompany this textbook.</p>

<p>Java is obligatory only for <localref href="graphics2d.5"/>.  For the material on
<word>OpenGL</word>&nbsp;1.1 in <localref href="gl1geom"/> and <localref href="gl1light"/>, 
either Java or C can be used.  Or, if you prefer JavaScript, you can use my glsim.js
(<localref href="gl1geom.6.3"/>), a JavaScript library that simulates a large part of OpenGL&nbsp;1.1.
But in any case, you will need to be at least somewhat familiar with
C to follow the discussion.  The <word>shader</word> programming language that is used
with <word>WebGL</word> is based on C, so some knowledge of C will also be useful
there.  (However, for writing WebGL shaders, you will not need to know one of the most
confusing aspects of C, namely the details of how it uses pointers).
JavaScript is essential for <word>WebGL</word> programming (<localref href="webgl"/> and <localref href="webgl3d"/>), 
for programming with <word>three.js</word> (<localref href="threejs"/>), and
for WebGPU (<localref href="webgpu"/>).  It is also used for
<word>HTML canvas</word> graphics in <localref href="graphics2d.6"/>.</p>

</intro>

=== davidjeck/graphicsbook/graphicstext/c03-gl1geom/intro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE intro SYSTEM "../graphicstext.dtd" >

<intro>

<p1>It is time to move on to computer graphics in three dimensions, although
it won't be until Section&nbsp;2 of this chapter that we really get into 3D.
You will find that many concepts from 2D graphics carry over to 3D, but the move into
the third dimension brings with it some new features that take a while to
get used to.</p1>

<p>Our focus will be <newword>OpenGL</newword>, a  graphics <word>API</word>
that was introduced in 1992 and has gone through many versions and many 
changes since then.  OpenGL is a  low-level graphics API, similar to the 2D APIs we have
covered.  It is even more primitive in some ways, but of course it is
complicated by the fact that it supports 3D.
OpenGL is the basis for <word>WebGL</word>, the current standard for 3D applications on the
Web that is covered in <localref href="webgl"/> and <localref href="webgl3d"/>.
There are many competing frameworks for
low-level 3D graphics, including Microsoft's <word>Direct3D</word>, 
Apple's <word>Metal</word>, and <word>Vulkan</word>, which
was designed by the creators of OpenGL as a more modern and efficient replacement.
</p>

<p>For the next two chapters, the discussion is
limited to OpenGL&nbsp;1.1.  OpenGL 1.1 is a large API, and we will 
only cover a part of it. The goal is to introduce 3D graphics concepts, 
not to fully cover the API.  A significant part of what we cover here
has been removed from the most modern versions of OpenGL, including WebGL.  However,
modern OpenGL in its pure form has a very steep initial learning curve,
and it is really not a good starting place for someone who is encountering
3D graphics for the first time.  Some additional support is needed&mdash;if not OpenGL 1.1
then some similar framework.  Since OpenGL 1.1 is
still supported, at least by all desktop implementations of OpenGL,
it's a reasonable place to start learning about 3D graphics.</p>

<p>This chapter concentrates on the geometric aspects of 3D graphics, such as defining
and transforming objects and projecting 3D scenes into 2D images.  The images that
we produce will look very unrealistic.  In the next chapter, we will see how to add
some realism by simulating the effects of lighting and of the material properties of surfaces.</p>

</intro>

=== davidjeck/graphicsbook/graphicstext/a3-gimp-inkscape/intro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE intro SYSTEM "../graphicstext.dtd" >

<intro>

<p1>Gimp and Inkscape are free and open-source programs for creating and
manipulating two-dimensional images.  Gimp is a <word>painting program</word>;
that is, it is primarily concerned with setting the colors of individual
pixels in an image.  Inkscape is a <word>drawing program</word>; that is,
it represents an image as a data structure that contains information
about the objects in a 2D scene.  The difference between painting and
drawing is discussed in <localref href="introduction.1"/>.
</p1>

<p>Even though the main focus of this book is on programming for three-dimensional
graphics, it can be useful to get some experience with 2D image manipulation programs.
Such programs illustrate some important concepts, such as color manipulation,
transparency, shape creation and editing, <word term="Bezier curve">Bezier curves</word>,
and (in drawing programs) grouping graphical objects into hierarchical structures.  And the
programs are often useful even in 3D graphics, for working with <word>texture</word> images.
This appendix offers just a very brief introduction to Gimp and Inkscape, but maybe
enough to let you start experimenting with the programs and to inspire you to learn more
about them from other sources.</p>

<p>When I taught computer graphics, I often included a few labs on Gimp and Inkscape. The material 
in this appendix was adapted from those labs.  While Gimp and Inkscape
are not quite the equivalent of the commercial programs Photoshop and Illustrator, they are
free, they can be used in serious graphics projects, and they have far more features than
can be covered in a couple of labs.</p>

</intro>
